server:
  port: 8778

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot2studysql?characterEncoding=UTF-8&useUnicode=true&serverTimezone=GMT%2B8
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database: mysql
      hibernate:
        dd1-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect


  servlet:
    multipart:
      max-file-size: 20MB

